import canonicalLaneMathlib.AdmissibleClass
import EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean.ShannonEntropyFoundation
import EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean.ChannelCapacity
import EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean.RateDistortionTheory
import EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean.SourceCodingTheorem
import EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean.GeographicInformationTheory

namespace HautevilleHouse
namespace EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean

def ConstrainedGeographicInformationClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_geographic_information_endgame (A : AdmissibleClass) :
    ConstrainedGeographicInformationClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end EarthScienceGeographicInformationScienceFoundationCanonicalLaneLean
end HautevilleHouse